language: java

jdk:
  - openjdk8

install:
  - chmod +x gradlew
  - ./gradlew jar

script:
  - java -jar ./build/libs/Script-BooruTagCN.jar

after_success:
  - mkdir push
  - cp ./KeyMap.json ./push/KeyMap.json
  - cp ./UserScript.user.js ./push/UserScript.user.js
  - cd ./push
  - git init
  - git config --global user.name "某亚瑟"
  - git config --global user.email "mouyase@qq.com"
  - git add .
  - git commit -m "Update"
  - git push --force "https://mouyase:${GIT_TOKEN}@github.com/4cy/Script-BooruTagCN.git" master:build

branches:
  only:
    - master